### ISSUE TITLE
Link to hayagriva examples

### ISSUE THREAD

**Issue by extua** [sitandr/typst-examples-book#10]
When adding to a bibliography, I often keep a tab open to the [example entries](https://github.com/typst/hayagriva/blob/main/tests/data/basic.yml) in the Hayagriva repository. I've mostly memorised the basics now, but still refer back to the examples from time to time.

I don't suggest copying the examples, but it would be worth linking to them to in this book. I find them really useful and think others would too.

**Comment by sitandr** [comment]
Thank you!
