### ISSUE TITLE
Overridden labels in diagraph

### ISSUE THREAD

**Issue by leyan** [sitandr/typst-examples-book#11]
Hi, there is a problem in the "Overridden labels" example in Diagraph, you did not include the labels dictionary so there is nothing overridden.

The actual example from the [package repo](https://github.com/Robotechnic/diagraph/blob/0d2da0dec4cbb7ede4ceb8bc604fbdf08dcbd668/examples/simplegraph.typ#L196) is: 

```````typ

#raw-render(
  ```
  digraph {
    rankdir=LR
    node[shape=circle]
    Hmm -> a_0
    Hmm -> big
    a_0 -> "a'" -> big [style="dashed"]
    big -> sum
  }
  ```,
  labels: (:
    big: [_some_#text(2em)[ big ]*text*],
    sum: $ sum_(i=0)^n 1/i $,
  ),
)
```````

**Comment by sitandr** [comment]
Thank you!

The problem is that this example doesn't work. On diagraph version 0.1.2, both in Web App and local, it produces an error:

```
error: unexpected argument: labels

    │
215 │ ╭   labels: (:
216 │ │     big: [_some_#text(2em)[ big ]*text*],
217 │ │     sum: $ sum_(i=0)^n 1/i $,
218 │ │   ),
    │ ╰───^
```

That is probably the reason I removed "labels" argument. I think we should create an issue in the `diagraph` repo. I will add a TODO for now.

**Comment by leyan** [comment]
It works in 0.2.0 though.

**Comment by sitandr** [comment]
Oh, thank you, I didn't notice that it was updated. I will fix that very soon!
