### ISSUE TITLE
Best practices for splitting large document

### ISSUE THREAD

**Issue by apraga** [sitandr/typst-examples-book#16]
**Location**: no idea, hence this issue 

**Importance**: everyone should split their work :)

**Discussion** from a conversation on [discord,](https://discord.com/channels/1054443721975922748/1208526599759204383) I'v learned that 

1. #include is the current best way to include sub-files like chapter
2. There are not preprocessing directives so using custom variables must be put in a template.typ

**Snippet**:
main.typ
```
#include "ch01-00-intro.typ"
#include "ch01-01-part1.typ"
```

ch01-00-intro.typ
```
#import "template.typ": *
#lorem(100)
```
template.typ
```
#let pcite =cite.with(form: "prose") 
```
I feel that this should be expanded to best practices in general but this is the only thing I've found so far :)

**Comment by sitandr** [comment]
This is a good note, I will certainly write about `include`. However, I have no ideas what else should I write about "best practices" with include and import.

Maybe also something about project structure or file naming?

**Comment by apraga** [comment]
Project structure would be nice. I feel it’s important to separate page layout (“set” rule) in a global configuration file for the project and local files that should be imported for each chapter. What’s that I struggled with when setting up a project.  Le dim. 18 févr. 2024 à 07:42, sitandr ***@***.***> a écrit :  
This is a good note, I will certainly write about include. However, I have no ideas what else should I write about "best practices" with include and import.
Maybe also something about project structure or file naming?
