### ISSUE TITLE
Number by current heading

### ISSUE THREAD

**Issue by laurmaedje** [sitandr/typst-examples-book#17]
**Location**: https://sitandr.github.io/typst-examples-book/book/snippets/math/numbering.html#numbering

**Importance**: The current math numbering snippet has two issues:
- It uses `locate` which discards the correct context provided to the numbering since Typst 0.11.
- It uses `counter(heading.where(level: 1))`, which isn't the idiomatic heading counter. It will count top-level headings, but ignore user-supplied `counter(heading).update(..)` updates.

**Snippet**: The snippet below fixes that:
```typ
#set math.equation(numbering: n => {
  let h1 = counter(heading).get().first()
  numbering("(1.1)", h1, n)
})
```

**Comment by sitandr** [comment]
Thanks a lot!

I'm planning to update all possible snippets to new context system eventually on myself, not sure about time though.

**Comment by Leedehai** [comment]
Hi - please see the comment on https://github.com/sitandr/typst-examples-book/commit/4a6adffc2b1ea950c383f757c06b867fefb4ce38 :)
