### ISSUE TITLE
Cannot build?

### ISSUE THREAD

**Issue by Leedehai** [sitandr/typst-examples-book#20]
At the commit a6e3053389f3d5595d956498a8f96a9411172208 "Some notes, new example and update".

Platform: macOS, Apple Silicon

```
$ typst --version
typst 0.11.0 (2bf9f95d)

$ mdbook --version
mdbook v0.4.37

$ mdbook build
2024-04-14 13:28:08 [INFO] (mdbook::book): Book building has started
Error at chapter "Placing, Moving, Scale & Hide"

error: cannot export multiple images without `{n}` in output path
Error at chapter "Tables & Grids"

error: cannot export multiple images without `{n}` in output path
Error at chapter "Tables & Grids"

error: cannot export multiple images without `{n}` in output path
Parsing error: Tried to use a ContextReference that has not bee resolved yet: ByScope { scope: <source.rust>, sub_context: None, with_escape: true }
2024-04-14 13:28:08 [ERROR] (mdbook::utils): Error: The "typst-highlight" preprocessor exited unsuccessfully with exit status: 1 status
```

Even if I clear the file content of the two chapters in basics/must_know/place.md and basics/must_know/tables.md, the last error ("Tried to use a ContextReference...") still remains.

**Comment by sitandr** [comment]
Are you sure you are using the last version of highlighter & renderer? Both issues seem like a thing that happened in its previous versions.

**Comment by Leedehai** [comment]
Hi - I'm not sure, in fact.. but I'm not sure how to check that, either. I simply `git pull`-ed in the repo and run `mdbook build` immediately. I also ran `cargo install mdbook` to ensure I'm have the most recent mdbook crate.

**Comment by sitandr** [comment]
You have to manually put in your PATH [this mdbook plugin](https://github.com/sitandr/mdbook-typst-highlight) for rendering to work properly. It seems that you have an old version somewhere, so mdbook is building the wrong way.
