### ISSUE TITLE
Try & Catch "maybe-image" broken in new Typst version

### ISSUE THREAD

**Issue by warstal** [sitandr/typst-examples-book#26]
Sadly, the locate function is deprecated in Typst 0.12.0: https://typst.app/docs/changelog/0.12.0/

This kills the genius Try & Catch function, which is documented here: https://sitandr.github.io/typst-examples-book/book/typstonomicon/try_catch.html

It would be really nice if there would be a different solution for this problem in the future.

**Comment by sitandr** [comment]
Hello, thank you for your issue! Sorry about missing it. I probably have some problems with notifications, I have to do something about it.

I've replaced the `locate` in the example with `context` at the first days of October. It seems to me that the currently online version of the book has the right example.

Please correct me if I'm wrong.
